### ISSUE TITLE
Python code for verifying maximum sockets both as  client or server

### ISSUE THREAD

**Issue by jynagire** [elabdesunil/python-socket-programming#2]
If sockets connection limits to particular number..how to write that code

**Comment by elabdesunil** [comment]
I think more information is needed first. 

1. If you are trying to set maximum no of connections allowed here is a [link](https://stackoverflow.com/a/35190128). Set LIMIT=max_allowed_count

2. Most socket interfaces have maximum number of sockets allowed predefined.

**Comment by elabdesunil** [comment]
I assume it's fixed
